### ISSUE TITLE
RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at ..\src\TH\THGeneral.c:218

### ISSUE THREAD

**Issue by mxg007** [bigdraw/myPointnet#1]
Dear friends:
I'm trying to run this train_tans.py.Error I'm getting...

F:\anaconda1\python.exe "C:/Users/123456/Desktop/PointNet/myPointnet-master_pytorch(Part Segmentation)/train_tans.py"
Namespace(batchSize=32, cuda=False, manualSeed=None, model='', nepoch=25, numPoints=2500, outf='seg', workers=4)
Random Seed:  5903
WARNING: You have a CUDA device, so you should probably run with --cuda
{'Chair': 0}
{'Chair': 0}
3371 375
[0: 0/105] train loss: -0.246559 accuracy: 0.239287
[0: 0/105] test loss: -0.251767 accuracy: 0.178250
Traceback (most recent call last):
  File "C:/Users/123456/Desktop/PointNet/myPointnet-master_pytorch(Part Segmentation)/train_tans.py", line 91, in <module>
    output = segmentor(points)  #现改的
  File "F:\anaconda1\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\123456\Desktop\PointNet\myPointnet-master_pytorch(Part Segmentation)\models.py", line 94, in forward
    trans64 = self.transform2(x)
  File "F:\anaconda1\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\123456\Desktop\PointNet\myPointnet-master_pytorch(Part Segmentation)\models.py", line 43, in forward
    x = self.MLP_MAX(x)
  File "F:\anaconda1\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\anaconda1\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "F:\anaconda1\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\anaconda1\lib\site-packages\torch\nn\modules\batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "F:\anaconda1\lib\site-packages\torch\nn\functional.py", line 1194, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at ..\src\TH\THGeneral.c:218

                                                                                                               PS: my RAM is 8 G

**Comment by bigdraw** [comment]
According to the hint given by the interpreter, I think the reason of this error is that your RAM is not sufficient to run the training process.

**Comment by mxg007** [comment]
@bigdraw I make it by changing the batchsize‘s size，such as batchsize = 16.
